/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_pearl_inn;

import com.sun.xml.internal.ws.api.server.Module;
import com.toedter.calendar.JDateChooser;
import java.awt.event.MouseEvent;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.scene.control.ToggleGroup;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static org.apache.commons.math3.fitting.leastsquares.LeastSquaresFactory.model;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Chathu_PC
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new object form Employee
     */
    Employee_class emp = new Employee_class(); 
//    DefaultTableModel dm;
   
    public Employee() {
        initComponents();
        
        
       
        //populate the jtable - fill the tbl
        emp.fillEmployeeJTable(jTable1);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonfemale);
        bg.add(jRadioButtonmale);
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(jRadioButtonper);
        bg1.add(jRadioButtoncon);
        jTextFieldempid.disable(); //disable txt box
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldaddress = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldempid = new javax.swing.JTextField();
        jTextFieldexde = new javax.swing.JTextField();
        jTextFielddes = new javax.swing.JTextField();
        jTextFielddep = new javax.swing.JTextField();
        jTextFieldbasicsal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldtele = new javax.swing.JTextField();
        jButtonrefresh = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        jButtonedit = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jLabel83 = new javax.swing.JLabel();
        jRadioButtonper = new javax.swing.JRadioButton();
        jRadioButtoncon = new javax.swing.JRadioButton();
        jDateChooserdob = new com.toedter.calendar.JDateChooser();
        jLabel86 = new javax.swing.JLabel();
        jButtonexpt = new javax.swing.JButton();
        jTextFieldsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1838, 1200));
        jPanel2.setMinimumSize(new java.awt.Dimension(1838, 1200));

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel69.setText("Name");

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel73.setText("Address");

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel74.setText("Email");

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel75.setText("Telephone");

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel77.setText("Employee ID");

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel79.setText("Experiance/Description");

        jLabel80.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel80.setText("Designation");

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel81.setText("Department");

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel82.setText("Basic Salary");

        jLabel84.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jLabel84.setText("Personal Infomation");

        jLabel85.setFont(new java.awt.Font("Sitka Small", 3, 18)); // NOI18N
        jLabel85.setText("Company Information");

        jTextFieldbasicsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldbasicsalKeyTyped(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "empid", "name", "Address", "email", "Tele", "Gender","DOB","exp", "Desg", "Dep", "Basicsal","EmpType"
            }
        )
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jTextFieldtele.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldteleActionPerformed(evt);
        }
    });
    jTextFieldtele.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            jTextFieldteleKeyTyped(evt);
        }
    });

    jButtonrefresh.setBackground(new java.awt.Color(102, 102, 255));
    jButtonrefresh.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jButtonrefresh.setText("Refresh");
    jButtonrefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonrefreshActionPerformed(evt);
        }
    });

    jButtonadd.setBackground(new java.awt.Color(102, 102, 255));
    jButtonadd.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jButtonadd.setText("Add");
    jButtonadd.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonaddActionPerformed(evt);
        }
    });

    jButtonedit.setBackground(new java.awt.Color(102, 102, 255));
    jButtonedit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jButtonedit.setText("Update");
    jButtonedit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtoneditActionPerformed(evt);
        }
    });

    jButtondelete.setBackground(new java.awt.Color(102, 102, 255));
    jButtondelete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jButtondelete.setText("Delete");
    jButtondelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtondeleteActionPerformed(evt);
        }
    });

    jButtonclear.setBackground(new java.awt.Color(102, 102, 255));
    jButtonclear.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jButtonclear.setText("Clear Fields");
    jButtonclear.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonclearActionPerformed(evt);
        }
    });

    jLabel78.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    jLabel78.setText("Gender");

    jRadioButtonmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jRadioButtonmale.setText("Male");

    jRadioButtonfemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jRadioButtonfemale.setText("Female");

    jLabel83.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    jLabel83.setText("Employee Type");

    jRadioButtonper.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jRadioButtonper.setText("Permenent");

    jRadioButtoncon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jRadioButtoncon.setText("Contract");

    jDateChooserdob.setDateFormatString("dd/MM/yyyy");

    jLabel86.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    jLabel86.setText("DOB");

    jButtonexpt.setBackground(new java.awt.Color(102, 102, 255));
    jButtonexpt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
    jButtonexpt.setText("Export the Employee Report");
    jButtonexpt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonexptActionPerformed(evt);
        }
    });

    jTextFieldsearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldsearchActionPerformed(evt);
        }
    });
    jTextFieldsearch.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextFieldsearchKeyReleased(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    jLabel1.setText("Search :-");

    jPanel1.setBackground(new java.awt.Color(51, 51, 255));

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    jLabel2.setText(" M A N A G E       E M P L O Y E E S ");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(449, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGap(426, 426, 426))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel85)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel76)
                                    .addGap(48, 48, 48)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel69)
                                        .addComponent(jLabel73)
                                        .addComponent(jLabel74)
                                        .addComponent(jLabel75)
                                        .addComponent(jLabel77)
                                        .addComponent(jLabel78)
                                        .addComponent(jLabel86))
                                    .addGap(89, 89, 89)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldempid, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jRadioButtonmale)
                                            .addGap(11, 11, 11)
                                            .addComponent(jRadioButtonfemale))
                                        .addComponent(jTextFieldaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                        .addComponent(jTextFieldemail)
                                        .addComponent(jTextFieldtele)
                                        .addComponent(jTextFieldname)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jButtonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jDateChooserdob, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel82)
                                    .addComponent(jLabel81)
                                    .addComponent(jLabel80)
                                    .addComponent(jLabel79)
                                    .addComponent(jLabel83))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldexde)
                                    .addComponent(jTextFielddes)
                                    .addComponent(jTextFielddep)
                                    .addComponent(jTextFieldbasicsal, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonper)
                                        .addGap(16, 16, 16)
                                        .addComponent(jRadioButtoncon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGap(52, 52, 52)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonexpt, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel84)
                    .addGap(29, 29, 29))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonexpt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel77)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel69)
                            .addGap(5, 5, 5)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel73)
                        .addComponent(jTextFieldaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel74)
                        .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel75)
                        .addComponent(jTextFieldtele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel78)
                        .addComponent(jRadioButtonmale)
                        .addComponent(jRadioButtonfemale))
                    .addGap(22, 22, 22)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel86)
                        .addComponent(jLabel76)
                        .addComponent(jDateChooserdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel85)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel79)
                        .addComponent(jTextFieldexde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(5, 5, 5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel80)
                        .addComponent(jTextFielddes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFielddep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel81))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldbasicsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel82))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel83)
                        .addComponent(jRadioButtonper)
                        .addComponent(jRadioButtoncon))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addComponent(jButtonrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(45, 45, 45))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1414, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 809, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //Insert
    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
         //get data from the fields
        String name= jTextFieldname.getText();
        String Address= jTextFieldaddress.getText();
        String email= jTextFieldemail.getText();
        String Tele= jTextFieldtele.getText();
        String Gender="Male";
        
        if(jRadioButtonfemale.isSelected()){
           Gender= "Female";
        }
        SimpleDateFormat dateFormat  = new SimpleDateFormat("YYYY-MM-dd");
        String DOB = dateFormat.format(jDateChooserdob.getDate());
        
        String exp= jTextFieldexde.getText();
        String Desg= jTextFielddes.getText();
        String Dep= jTextFielddep.getText();
        String Basicsal= jTextFieldbasicsal.getText();
        String EmpType="Permenent";
        
        if(jRadioButtoncon.isSelected()){
           EmpType= "Contract";
        }
        
        //validations
       Pattern p = Pattern.compile("^[0-9][0-9]{9}$");
       Matcher m = p.matcher(jTextFieldtele.getText());
       
       Pattern p2 = Pattern.compile("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$");
       Matcher m2 = p2.matcher(jTextFieldemail.getText());
        
       //not null
        if(name.trim().equals("")|| Address.trim().equals("")|| email.trim().equals("")|| Tele.trim().equals("") || exp.trim().equals("")|| Desg.trim().equals("")|| Basicsal.trim().equals("")|| Gender.trim().equals("")|| EmpType.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Required Fields", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }else{
            if(!m2.matches()){
                JOptionPane.showMessageDialog(null,"Invalid email");
        }else{
            if(!m.matches()){
                JOptionPane.showMessageDialog(null,"Invalid Mobile Number");
            }else{
            if(emp.addEmployee(name, Address, email, Tele,Gender,DOB ,exp, Desg, Dep, Basicsal,EmpType)){
            JOptionPane.showMessageDialog(rootPane, "New Employee Added Successfully", "Add Employee", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Employee not Added", "Add Employee Error", JOptionPane.ERROR_MESSAGE);
            
        }}}
        }
    }//GEN-LAST:event_jButtonaddActionPerformed

    //update
    private void jButtoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditActionPerformed
       //get data from the fields
        int empid = 0;
        String name= jTextFieldname.getText();
        String Address= jTextFieldaddress.getText();
        String email= jTextFieldemail.getText();
        String Tele= jTextFieldtele.getText();
        String Gender= "Male";
        
        if(jRadioButtonfemale.isSelected()){
            Gender= "Female";
        }
        SimpleDateFormat dateFormat  = new SimpleDateFormat("YYYY-MM-dd");
        String DOB = dateFormat.format(jDateChooserdob.getDate());
        
        String exp= jTextFieldexde.getText();
        String Desg= jTextFielddes.getText();
        String Dep= jTextFielddep.getText();
        String Basicsal= jTextFieldbasicsal.getText();
        String EmpType="Permenent";
        
        if(jRadioButtoncon.isSelected()){
           EmpType= "Contract";
        }
        
        //validations
       Pattern p = Pattern.compile("^[0-9][0-9]{9}$");
       Matcher m = p.matcher(jTextFieldtele.getText());
       
       Pattern p2 = Pattern.compile("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$");
       Matcher m2 = p2.matcher(jTextFieldemail.getText());
        
        if(name.trim().equals("")|| Address.trim().equals("")|| email.trim().equals("")|| Tele.trim().equals("") || exp.trim().equals("")|| Desg.trim().equals("")|| Basicsal.trim().equals("")|| Gender.trim().equals("")|| EmpType.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "All Fields are Required", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        }else{
            if(!m2.matches()){
                JOptionPane.showMessageDialog(null,"Invalid email");
        }else{
                if(!m.matches()){
                JOptionPane.showMessageDialog(null,"Invalid Mobile Number");
            }
        else{
            try{
                empid = Integer.valueOf(jTextFieldempid.getText()); 
            }catch(NumberFormatException ex ){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+"- Enter the Employee ID(number)","Employee ID Error ", JOptionPane.WARNING_MESSAGE);
            }
        }
            if(emp.editEmployee(empid, name, Address, email, Tele,Gender,DOB , exp, Desg, Dep, Basicsal,EmpType)){
            JOptionPane.showMessageDialog(rootPane, "Employee Updateded Successfully", "Updateded Employee", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Employee not Updateded", "Updateded Employee Error", JOptionPane.ERROR_MESSAGE);
            
        }}}
    }//GEN-LAST:event_jButtoneditActionPerformed

    //mouse click - add data to fields
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       //get the jtable model
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        //get the selected raw indexes
        int rIndex = jTable1.getSelectedRow();
        
        //display data
        jTextFieldempid.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldname.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldaddress.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldemail.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldtele.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldexde.setText(model.getValueAt(rIndex, 7).toString());
        jTextFielddes.setText(model.getValueAt(rIndex, 8).toString());
        jTextFielddep.setText(model.getValueAt(rIndex, 9).toString());
        jTextFieldbasicsal.setText(model.getValueAt(rIndex, 10).toString());
        
         String Gender = model.getValueAt(rIndex, 5).toString();
        
        if(Gender.equals("Female")){
            jRadioButtonfemale.setSelected(true);
        }else if(Gender.equals("Male")){
            jRadioButtonmale.setSelected(true);
        }
        
        String EmpType = model.getValueAt(rIndex, 11).toString();
        
        if(EmpType.equals("Contract")){
            jRadioButtoncon.setSelected(true);
        }else if(EmpType.equals("Permenent")){
            jRadioButtonper.setSelected(true);
        }
        
        try{
        Date DOB =  new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rIndex, 6).toString());
        jDateChooserdob.setDate(DOB);
        }catch(Exception ex){
            Logger.getLogger(Employee_class.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jTable1MouseClicked

    //clear fields
    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
      // remove text from all the jtextboxes
        jTextFieldempid.setText("");
        jTextFieldname.setText("");
        jTextFieldaddress.setText("");
        jTextFieldemail.setText("");        
        jTextFieldtele.setText("");  
        jRadioButtonfemale.setSelected(false);
        jTextFieldexde.setText("");
        jTextFielddes.setText("");
        jTextFielddep.setText("");
        jTextFieldbasicsal.setText("");
        jRadioButtoncon.setSelected(false);
        jDateChooserdob.setDate(null);
        
    }//GEN-LAST:event_jButtonclearActionPerformed

    //delete
    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
         // delete the selected client
        try{
               int id = Integer.valueOf(jTextFieldempid.getText()); 
               
               if(emp.removeEmployee(id)){
                    JOptionPane.showMessageDialog(rootPane, "Employee Removed Successfully", "Remove Employee", JOptionPane.INFORMATION_MESSAGE);
               }else{
                    JOptionPane.showMessageDialog(rootPane, "Employee not Remved", "Removed Employee Error", JOptionPane.ERROR_MESSAGE);
            
        }
            }catch(NumberFormatException ex ){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+"- Enter the Employee ID(number)","Employee ID Error ", JOptionPane.WARNING_MESSAGE);
            }
       
    }//GEN-LAST:event_jButtondeleteActionPerformed

    //refresh and fill the table
    private void jButtonrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrefreshActionPerformed
          //clear the jtable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"empid", "name", "Address", "email", "Tele", "Gender","DOB","exp", "Desg", "Dep", "Basicsal","EmpType"} ));

        //populate the jtable
        emp.fillEmployeeJTable(jTable1);
    }//GEN-LAST:event_jButtonrefreshActionPerformed

    //start of filter - search
//    public void CreateColumns(){
//        //get table model
//        dm = (DefaultTableModel) jTable1.getModel();
//        
//        //Add cols
//        dm.addColumn("empid");
//        dm.addColumn("name");
//        dm.addColumn("Address");
//        dm.addColumn("email");
//        dm.addColumn("Tele");
//        dm.addColumn("Gender");
//        dm.addColumn("DOB");
//        dm.addColumn("exp");
//        dm.addColumn("Desg");
//        dm.addColumn("Dep");
//        dm.addColumn("Basicsal");
//        dm.addColumn("EmpType");
//        
//        
//    }
    //Add rows data
//    private void Populate(String empid,String name,String Address, String email,String Tele,String Gender,String DOB, String exp, String Desg,String Dep, String Basicsal,String EmpType){
//        String[] rowData = (empid,name,Address, email, Tele,Gender,DOB,exp,Desg,Dep,Basicsal,EmpType);
//        dm.addRow(rowData);
//    }
    
//    private void filter(String query){
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (dm);
//        jTable1.setRowSorter(tr);
//        
//        tr.setRowFilter(RowFilter.regexFilter(query));
//        
//        
//    }

    
    //validation - phone nbr text box key
    private void jTextFieldteleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldteleKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    
    }//GEN-LAST:event_jTextFieldteleKeyTyped

    //validation - basic sal
    private void jTextFieldbasicsalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldbasicsalKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldbasicsalKeyTyped

    //export to excel sheet
    private void jButtonexptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexptActionPerformed
        FileOutputStream excelFOU = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook excelJTableExporter = null;
        
        JFileChooser excelfilecChooser = new JFileChooser("C:\\Users\\Administrator\\Downloads");
        excelfilecChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Excel Files", "xls","xlsx","xlsm");
        excelfilecChooser.setFileFilter(fnef);
        int excelchoocer =  excelfilecChooser.showSaveDialog(null);
        
        if(excelchoocer == JFileChooser.APPROVE_OPTION){
            
            try {
                //Employee_class excelJTableExporter = new Employee_class();
                excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable Sheet");
                for(int i = 0; i <jTable1.getRowCount(); i++){
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for(int j = 0; j< jTable1.getColumnCount(); j++){
                        XSSFCell excelCell = excelRow.createCell(j);
                        
                        excelCell.setCellValue(jTable1.getValueAt(i,j).toString());
                        
                    }
                }   
                excelFOU = new FileOutputStream(excelfilecChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(null,"Exported Successfully ");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try { 
                    if(excelBOU != null){
                        excelBOU.close();
                    }
                    if(excelFOU != null){
                        excelFOU.close();
                    }
                    if(excelJTableExporter != null){
                        excelJTableExporter.close();
                    }
                    
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButtonexptActionPerformed

    private void jTextFieldteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldteleActionPerformed
        // TODO add your handling code here:
//        String sPhoneNumber = "605-8889999";
//    Pattern pattern = Pattern.compile("[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]");
//      Matcher matcher = pattern.matcher(sPhoneNumber);
//
//      if (matcher.matches()) {
//          JOptionPane.showMessageDialog(rootPane, "Phone Number valid", "Validate Phone", JOptionPane.ERROR_MESSAGE);
////          System.out.println("Phone Number Valid");
//      } else {
//          JOptionPane.showMessageDialog(rootPane, "Phone number must be in xxx-xxxxxxx", "Invalidate Phone", JOptionPane.ERROR_MESSAGE);
//      }
    }//GEN-LAST:event_jTextFieldteleActionPerformed

    //search
    private void jTextFieldsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldsearchKeyReleased
        
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       String search = jTextFieldsearch.getText().toLowerCase();
        
       TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
       jTable1.setRowSorter(tr);
       tr.setRowFilter(RowFilter.regexFilter(search));
        
    }//GEN-LAST:event_jTextFieldsearchKeyReleased

    private void jTextFieldsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonedit;
    private javax.swing.JButton jButtonexpt;
    private javax.swing.JButton jButtonrefresh;
    private com.toedter.calendar.JDateChooser jDateChooserdob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtoncon;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JRadioButton jRadioButtonper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldaddress;
    private javax.swing.JTextField jTextFieldbasicsal;
    private javax.swing.JTextField jTextFielddep;
    private javax.swing.JTextField jTextFielddes;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldempid;
    private javax.swing.JTextField jTextFieldexde;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldsearch;
    private javax.swing.JTextField jTextFieldtele;
    // End of variables declaration//GEN-END:variables

    private Connection getConnection() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
